import React from 'react';
import { 
  Activity, 
  Brain, 
  ShieldAlert, 
  Database, 
  Cpu, 
  CheckCircle2, 
  Layers, 
  FileText, 
  HelpCircle,
  ExternalLink,
  Lock,
  Stethoscope,
  Heart
} from 'lucide-react';
import { CONDITIONS_KNOWLEDGE_BASE } from '../lib/knowledgeBase';

export default function AboutPage({ setActivePage }) {
  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-12 animate-fade-in">
      {/* Header */}
      <div className="text-center space-y-3 max-w-3xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-teal-500/10 border border-teal-500/30 text-teal-300 text-xs font-semibold">
          <Brain className="w-3.5 h-3.5 text-teal-400" />
          <span>System Architecture & Clinical Specifications</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          About MediLogic AI
        </h1>
        <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
          MediLogic AI is an educational medical diagnosis expert system designed to illustrate how deterministic forward-chaining clinical rules and probabilistic symptom scoring function in modern biomedical informatics.
        </p>
      </div>

      {/* Mandatory Medical Disclaimer Banner */}
      <div className="glass-panel rounded-3xl p-6 sm:p-8 border border-rose-900/40 bg-gradient-to-r from-rose-950/40 via-slate-900 to-rose-950/40 space-y-3">
        <div className="flex items-center gap-2.5 text-rose-300 font-bold text-sm">
          <ShieldAlert className="w-5 h-5 text-rose-400" />
          <span>Comprehensive Educational & Clinical Disclaimer</span>
        </div>
        <p className="text-xs text-slate-300 leading-relaxed">
          MediLogic AI is strictly an educational tool and software architecture demonstration. It does <strong>not</strong> provide medical diagnoses, clinical treatment plans, or prescriptions. All inferences generated by this system are based on predefined rule heuristics and must never replace the professional judgment, consultation, or diagnosis of a licensed physician or healthcare provider.
        </p>
        <p className="text-xs text-rose-200/90 font-medium">
          If you or someone you are caring for is experiencing severe acute chest pain, shortness of breath, acute stroke signs, sudden loss of consciousness, or uncontrollable bleeding, immediately dial your local emergency services (e.g. 911 in North America, 112 in Europe) or visit the nearest emergency department.
        </p>
      </div>

      {/* 3 Pillars Architecture */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-panel rounded-2xl p-6 border border-slate-800 space-y-3">
          <div className="p-3 rounded-xl bg-teal-500/10 text-teal-400 w-fit">
            <Cpu className="w-5 h-5" />
          </div>
          <h3 className="font-bold text-base text-white">Rule-Based Expert Engine</h3>
          <p className="text-xs text-slate-400 leading-relaxed">
            Utilizes forward-chaining deduction. Symptoms are evaluated against required, characteristic, and optional weighting matrices with transparent reasoning traces.
          </p>
        </div>

        <div className="glass-panel rounded-2xl p-6 border border-slate-800 space-y-3">
          <div className="p-3 rounded-xl bg-cyan-500/10 text-cyan-400 w-fit">
            <Database className="w-5 h-5" />
          </div>
          <h3 className="font-bold text-base text-white">InsForge PostgreSQL Backend</h3>
          <p className="text-xs text-slate-400 leading-relaxed">
            All patient records, assessment histories, and user profiles are securely persisted using InsForge's official BaaS PostgreSQL database and PostgREST API.
          </p>
        </div>

        <div className="glass-panel rounded-2xl p-6 border border-slate-800 space-y-3">
          <div className="p-3 rounded-xl bg-indigo-500/10 text-indigo-400 w-fit">
            <Lock className="w-5 h-5" />
          </div>
          <h3 className="font-bold text-base text-white">InsForge Auth & Security</h3>
          <p className="text-xs text-slate-400 leading-relaxed">
            Built-in JWT authentication, user registration, encrypted credentials, and session persistence without manual password storage.
          </p>
        </div>
      </div>

      {/* Disease Models Catalog */}
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-white tracking-tight">
              Predefined Disease Knowledge Base
            </h2>
            <p className="text-xs text-slate-400">
              {CONDITIONS_KNOWLEDGE_BASE.length} clinical conditions actively modeled in the rule engine.
            </p>
          </div>
          <button
            onClick={() => setActivePage('symptoms')}
            className="px-4 py-2 rounded-xl bg-teal-600 hover:bg-teal-500 text-white text-xs font-semibold shadow-md shadow-teal-500/20 transition-all"
          >
            Test Symptoms
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {CONDITIONS_KNOWLEDGE_BASE.map(cond => (
            <div key={cond.id} className="glass-panel rounded-2xl p-5 border border-slate-800 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-bold uppercase px-2 py-0.5 rounded bg-slate-900 border border-slate-800 text-teal-300">
                  {cond.category}
                </span>
                <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded ${
                  cond.riskLevel === 'emergency'
                    ? 'bg-rose-500/20 text-rose-300 border border-rose-500/40'
                    : cond.riskLevel === 'high'
                    ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40'
                    : 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                }`}>
                  {cond.riskLevel}
                </span>
              </div>

              <div>
                <h4 className="font-bold text-sm text-white">{cond.name}</h4>
                <p className="text-xs text-slate-400 mt-1 line-clamp-2">{cond.description}</p>
              </div>

              <div className="pt-2 border-t border-slate-800/80 text-[11px] text-slate-500 space-y-1">
                <div>Specialist: <span className="text-slate-300">{cond.recommendedSpecialist}</span></div>
                <div>Triage: <span className="text-slate-300">{cond.triageLevel}</span></div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
